# This is a standard template for a wandb sweep.
# See: https://docs.wandb.ai/guides/sweeps/define-sweep-configuration
#
# Sweeps can be initialized with retinal-rl from the command line with:
#
# python main.py +experiment=vae-classification command=sweep sweep.config_name=bottle-weight-sweep



description: Sweep over the VAE bottle_weight (KL divergence weight) for the vae-classification experiment.
program: main.py
method: grid
project: retinal-vae # Project name from vae-classification.yaml


parameters:
  # The parameter to sweep over.
  bottle_weight:
    values: [0.0001, 0.001, 0.01, 0.1, 1, 10.0]
  # Ensure wandb is enabled for all sweep runs.
  logging.use_wandb:
    value: True
