objects:
  distractor:
    init: 40
    delay: 30
    actors:
      distractor-1:
        textures:
          - 'mnist/six'
      distractor-2:
        textures:
          - 'mnist/seven'
      distractor-3:
        textures:
          - 'mnist/eight'
      distractor-4:
        textures:
          - 'mnist/nine'
      distractor-5:
        textures:
          - 'mnist/zero'
      distractor-6:
        textures:
          - 'mnist/five'
      distractor-7:
        textures:
          - 'mnist/four'
      distractor-8:
        textures:
          - 'mnist/three'
      distractor-9:
        textures:
          - 'mnist/two'
      distractor-0:
        textures:
          - 'mnist/one'
