# Configuration for the CIFAR10 dataset in classification experiments.

name: cifar10  # Name of the dataset

imageset:
  _target_: retinal_rl.classification.imageset.Imageset
  source_transforms:
    - _target_: retinal_rl.classification.transforms.ScaleShiftTransform
      vision_width: ${vision_width}
      vision_height: ${vision_height}
      image_rescale_range: ${image_rescale_range}
  noise_transforms:
    - _target_: retinal_rl.classification.transforms.ShotNoiseTransform
      lambda_range:
        - ${eval:"5 if ${shot_noise_transform} else 0"}
        - ${eval:"50 if ${shot_noise_transform} else 0"}
    - _target_: retinal_rl.classification.transforms.ContrastTransform
      contrast_range:
        - ${eval:"0.6 if ${contrast_noise_transform} else 1"}
        - ${eval:"1.4 if ${contrast_noise_transform} else 1"}
    - _target_: retinal_rl.classification.transforms.IlluminationTransform
      brightness_range:
        - ${eval:"0.6 if ${brightness_noise_transform} else 1"}
        - ${eval:"1.4 if ${brightness_noise_transform} else 1"}
    - _target_: retinal_rl.classification.transforms.BlurTransform
      blur_range:
        - ${eval:"0 if ${blur_noise_transform} else 0"}
        - ${eval:"2 if ${blur_noise_transform} else 0"}
  apply_normalization: true
  fixed_transformation: false
  multiplier: 1
