# Number of training epochs
num_epochs: 200

# The optimizer to use
optimizer: # torch.optim Class and parameters
  _target_: torch.optim.AdamW
  lr: 0.0003
  weight_decay: ${weight_decay}

# The objective function
objective:
  _target_: retinal_rl.models.objective.Objective
  losses:
    - _target_: retinal_rl.classification.loss.ClassificationLoss
      target_circuits: # Circuit parameters to optimize with this optimizer.  We train the retina and the decoder exclusively to maximize reconstruction
        - retina
        - thalamus
        - visual_cortex
        - inferotemporal
        - prefrontal
        - classifier
      weights:
        - ${eval:'1-${recon_weight_retina}'}
        - ${eval:'1-${recon_weight_thalamus}'}
        - ${eval:'1-${recon_weight_cortex}'}
        - 1
        - 1
        - 1
    - _target_: retinal_rl.models.loss.ReconstructionLoss
      target_decoder: "v1_decoder"
      target_circuits: # Circuit parameters to optimize with this optimizer.  We train the retina and the decoder exclusively to maximize reconstruction
        - retina
        - thalamus
        - visual_cortex
        - inferotemporal
        - it_decoder
        - v1_decoder
      weights:
        - ${recon_weight_retina}
        - ${recon_weight_thalamus}
        - ${recon_weight_cortex}
        - ${recon_weight_cortex}
        - 1
        - 1
    - _target_: retinal_rl.models.loss.L1Sparsity
      target_response: "visual_cortex"
      target_circuits:
        - retina
        - thalamus
        - visual_cortex
        - inferotemporal
      weights:
        - ${sparsity_weight}
        - ${sparsity_weight}
        - ${sparsity_weight}
        - ${sparsity_weight}
  logging_statistics:
    - _target_: retinal_rl.classification.loss.PercentCorrect
