# Optimizer configuration for VAE classification

# Number of training epochs
num_epochs: 200

# The optimizer to use
optimizer: # torch.optim Class and parameters
  _target_: torch.optim.AdamW
  lr: 0.0003
  weight_decay: ${weight_decay}

# The multi-objective function for VAE
objective:
  _target_: retinal_rl.models.objective.Objective
  losses:
    # Task loss: Classification
    - _target_: retinal_rl.classification.loss.ClassificationLoss
      target_circuits: # All circuits involved in the forward pass
        - retina
        - thalamus
        - visual_cortex
        - vae_bottleneck
        - latent_sampler
        - prefrontal
        - classifier
      weights:
        - ${eval:'1-${recon_weight_retina}'}
        - ${eval:'1-${recon_weight_thalamus}'}
        - ${eval:'1-${recon_weight_cortex}'}
        - 1  # VAE bottleneck
        - 1  # Latent sampler
        - 1  # Prefrontal
        - 1  # Classifier
    
    # Reconstruction loss
    - _target_: retinal_rl.models.loss.ReconstructionLoss
      target_decoder: "v1_decoder"
      target_circuits: # Circuits involved in reconstruction
        - retina
        - thalamus
        - visual_cortex
        - vae_bottleneck
        - latent_sampler
        - v1_decoder
      weights:
        - ${eval:'${recon_weight_retina} * ${lambda_recon}'}
        - ${eval:'${recon_weight_thalamus} * ${lambda_recon}'}
        - ${eval:'${recon_weight_cortex} * ${lambda_recon}'}
        - ${lambda_recon}  # VAE bottleneck
        - ${lambda_recon}  # Latent sampler
        - ${lambda_recon}  # Decoder
    
    # KL divergence loss (Information Bottleneck)
    - _target_: retinal_rl.models.loss.KLDivergenceLoss
      target_bottleneck: "vae_bottleneck"
      beta: ${lambda_ib}  # Information bottleneck weight
      target_circuits:
        - vae_bottleneck
        - latent_sampler
      weights:
        - 1.0
        - 1.0
    
    # L1 sparsity on visual cortex (optional but recommended)
    - _target_: retinal_rl.models.loss.L1Sparsity
      target_response: "visual_cortex"
      target_circuits:
        - retina
        - thalamus
        - visual_cortex
      weights:
        - ${sparsity_weight}
        - ${sparsity_weight}
        - ${sparsity_weight}
        
  logging_statistics:
    - _target_: retinal_rl.classification.loss.PercentCorrect
