name: training-parameters
description: Testing how the presence of distractors effects network performance.
program: train.py
method: grid
project: retinal-rl
parameters:
  network:
    value: "complex"
  env:
    value: "gathering_cifar"
  repeat:
    distribution: "int_uniform"
    min: 1
    max: 2
  num_workers:
    value: 24
  num_envs_per_worker:
    value: 8
  wide_aspect_ratio:
    value: False
  res_h:
    value: 90
  res_w:
    value: 120
  train_for_env_steps:
    value: 1000000000
  use_rnn:
    value: "False"
  rnn_size:
    value: 64
  with_vtrace:
    values: [False,True]
  exploration_loss_coeff:
    values: [0,0.001,0.1]
  learning_rate:
    values: [0.001,0.0001,0.00001]
  lr_schedule:
    values: ["constant","kl_adaptive_minibatch"]
  activation:
    values: ["elu", "relu", "tanh"]
  normalize_returns:
    value: False
  rollout:
    value: 32
  recurrence:
    value: 32
  experiment:
    value: "{activation}_{lr_schedule}_{learning_rate}_{exploration_loss_coeff}_{with_vtrace}_{repeat}"
  train_dir:
    value: "./train_dir/training-parameters"
